[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"


[project]
name = "mcp-package-scanner"
version = "0.1.0"
dependencies = [
    "packaging",
    "requests"
]


[project.scripts]
mcp-scan = "mcp_package_scanner.cli:main"


[tool.setuptools.packages.find]
where = ["src"]